# Lang
export LANG=en_US.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_TIME=en_US.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Go setting
export GOPATH=$HOME/go
export CGO_CFLAGS_ALLOW=-Xpreprocessor
export GIT_TERMINAL_PROMPT=1
export PATH=$HOME/go/bin:$PATH

# Node
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="/usr/local/opt/node@12/bin:$PATH"

# Rust
source $HOME/.cargo/env

#ssh
#export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7891

# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --follow --glob "!.git/*"'

